global using FullArcheticture_WebApiLab.Data;
global using FullArcheticture_WebApiLab.Models;
global using FullArcheticture_WebApiLab.Repository.Implement;
global using FullArcheticture_WebApiLab.Repository.Interface;
global using FullArcheticture_WebApiLab.Services.Implement;
global using FullArcheticture_WebApiLab.Services.Interface;
global using FullArcheticture_WebApiLab.UnitOfWorks;
