// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Day18WizardLab.Models;

[Keyless]
[Table("COAL")]
public partial class COAL
{
    public int? ID { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string FirstName { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string MiddleName { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string LastName { get; set; }
}