// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Day18WizardLab.Models;

[Keyless]
[Table("E1")]
public partial class E1
{
    public int OrderId { get; set; }

    public int? EmployeeID { get; set; }

    public int? orderYear { get; set; }
}