// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Day18WizardLab.Models;

[Keyless]
[Table("p1")]
public partial class p1
{
    [Required]
    [StringLength(15)]
    public string CategoryName { get; set; }

    public short Quantity { get; set; }

    public int? OrderYear { get; set; }
}