// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Day18WizardLab.Models;

[Keyless]
[Table("p2")]
public partial class p2
{
    [Required]
    [StringLength(15)]
    public string Categoryname { get; set; }

    [Column("1996")]
    public int? _1996 { get; set; }

    [Column("1997")]
    public int? _1997 { get; set; }

    [Column("1998")]
    public int? _1998 { get; set; }
}