// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Day18WizardLab.Models;

[Keyless]
public partial class SouqCustomer
{
    public int? CustomerID { get; set; }

    [StringLength(50)]
    public string FirstName { get; set; }

    [StringLength(50)]
    public string LirstName { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Mail { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string City { get; set; }
}