// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Day18WizardLab.Models;

[Keyless]
[Table("t1")]
public partial class t1
{
    [StringLength(10)]
    public string CustomerName { get; set; }

    [StringLength(10)]
    public string ProductName { get; set; }

    [Column(TypeName = "decimal(9, 2)")]
    public decimal? Price { get; set; }
}